apiVersion: v1
kind: Service
metadata:
  name: backend1-service
  namespace: verified-backend
  labels:
    app: backend1
spec:
  selector:
    app: backend1
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  type: ClusterIP
